# Generated by Django 3.2.15 on 2023-03-09 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_pmnf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagem',
            name='sala',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='chat_pmnf.sala', verbose_name='sala'),
        ),
    ]
