# Generated by Django 3.2.15 on 2023-03-09 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat_pmnf', '0002_alter_messagem_sala'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='messagem',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_pmnf.sala', verbose_name='sala'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='participante',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
